/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package databox.importer;

public class MainControlerTest {

	/*
	 * @Test public void testInitialization() { MainControllerHolder controler = new MainControllerHolder(); assertTrue("Controler initialization should return 'true'", controler.initialize()); }
	 */
}
